variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - scan

# Include CI templates 
include:
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/cicd-variables.yml"

  - local: "cicd/gitlab-ci/python-lint.yml"
  - local: "cicd/gitlab-ci/python-test.yml"

  # # Docs pages
  # - project: "ska-telescope/templates-repository"
  #   file: "gitlab-ci/includes/docs.gitlab-ci.yml"

  # .post step finalisers e.g.: badges
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"

python-test:
  rules:
    - when: manual
      allow_failure: true
