variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - scan

include:
- project: ska-telescope/templates-repository
  file: 
  - gitlab-ci/includes/finaliser.gitlab-ci.yml
- project: ska-telescope/ska-python-uv
  file:
  - gitlab-ci/python-lint.yml
  - gitlab-ci/python-test.yml
  # - gitlab-ci/docs-build.yml

python-test:
  rules:
    - when: manual
      allow_failure: true
