FROM ghcr.io/astral-sh/uv:debian

ARG USERNAME=jirachecker
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USERNAME

USER $USERNAME
